[workspace]
resolver = "3"
members = ["crates/cli", "crates/locus", "crates/macro"]

[workspace.package]
version = "0.0.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/PerishLab/locus"

[workspace.dependencies]
clap = { version = "4", features = ["derive"] }
getrandom = "0.3"
locus = { path = "crates/locus", version = "=0.0.0", registry = "perish" }
locus-macro = { path = "crates/macro", version = "=0.0.0", registry = "perish" }
plumb = { version = "0", registry = "perish" }
proc-macro2 = "1"
quote = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
syn = { version = "2", features = ["full"] }
toml = "0.9"
